FROM ubuntu:bionic

RUN apt update && apt install -y curl

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

RUN /root/.cargo/bin/rustup target add aarch64-unknown-linux-gnu

RUN echo "[target.aarch64-unknown-linux-gnu]\nlinker = \"aarch64-linux-gnu-gcc\"" > /root/.cargo/config

RUN apt install -y nodejs yarn python build-essential cmake make wget 

RUN apt -yq --no-install-suggests --no-install-recommends install g++-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-7-multilib libc6-arm64-cross libssl-dev 

RUN wget https://www.openssl.org/source/openssl-1.0.2l.tar.gz && tar xzf openssl-1.0.2l.tar.gz

RUN cd openssl-1.0.2l && ./Configure --prefix=$HOME/openssl os/compiler:aarch64-linux-gnu && \
    make CC="aarch64-linux-gnu-gcc" AR="aarch64-linux-gnu-ar r" RANLIB="aarch64-linux-gnu-ranlib" && \
    make install

WORKDIR /fly.rs

CMD "/bin/bash"